version: "3"

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
  product-service:
    build: ./product-service
    ports:
      - "8002:8002"
  order-service:
    build: ./order-service
    ports:
      - "8003:8003"
